apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    name: webapp-deployment
spec:
  template:
    metadata:
      name: webapp
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: nginx
        volumeMounts:
        - name: my-vol
          mountPath: /var/www/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: my-vol
        persistentVolumeClaim:
          claimName: myclaim
  replicas: 2
  selector:
    matchLabels:
      name: webapp