apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - name: configmap-vol
      mountPath: /usr/local
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: configmap-vol
    configMap:
      name: configmap
