apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
  - name: webapp
    image: nginx
    volumeMounts:
    - name: my-vol
      mountPath: /var/www/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      claimName: myclaim